### PR TITLE
Fix some Swift 6 warnings

### PR DESCRIPTION
**Pull request by stephencelis**
We have a couple warnings when building in Xcode 16.

### CODE REVIEW

**Comment by stephencelis** [comment]
@finestructure While updating things for the beta, we realized that `--static-swift-stdlib` has been broken on Swift 5.9+ for awhile now. The failures are a little cryptic and we're not sure how to fix, so I'm removing it from CI for now, but if you still have a need to support it, we'd be happy to take a new PR to fix!

**Comment by finestructure** [comment]
Thanks for the ping, @stephencelis ! Broken how? Because we're still using the flag in our linux builds (although in a project where we don't yet use swift-dependencies, but will very soon).

**Comment by stephencelis** [comment]
@finestructure I haven't dug into it too deeply, but I think when Windows dynamic linking support was added it stopped working. If you are able to get things working, though, please let us know!

**Comment by finestructure** [comment]
Will do!

**Pull request merged**
