### PR TITLE
Fix autoclosure endpoints

### LINKED ISSUE #155: `@DependencyClient` and `@autoclosure` parameters
### Description

This is similar to https://github.com/pointfreeco/swift-dependencies/issues/146. The code generated by `@DependencyClient` is incorrect for `@autoclosure` parameters and generate invalid swift code. it should explicitly refuse to generate code or if possible generate valid code.

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-dependencies/issues) or [discussion](https://github.com/pointfreeco/swift-dependencies/discussions).

### Expected behavior

```swift
@DependencyClient
public struct DemoClinet {
    public var execute: (_ closure: @autoclosure () -> String) -> Void
}
```

Should generate valid swift code

### Actual behavior

The code generated :

```swift
public func execute(closure p0: @autoclosure () -> String) -> Void {
    self.execute(p0)  // Error occurs: 'Add () to forward @autoclosure parameter'
}

private var _execute: (_ closure: @autoclosure () -> String) -> Void = { _ in
    XCTestDynamicOverlay.XCTFail("Unimplemented: 'execute'")
}
```

is not valid code: `Add () to forward @autoclosure parameter`

### Steps to reproduce

_No response_

### Dependencies version information

1.1.2

### Destination operating system

_No response_

### Xcode version information

15.0.0

### Swift Compiler version information

_No response_

### PR DESCRIPTION
**Pull request by mbrandonw**
Fixes #155.

### CODE REVIEW

**Comment by xiii111** [comment]
@mbrandonw https://github.com/pointfreeco/swift-dependencies/issues/155#issuecomment-1839858429

> so if I can't finish it by the end of this week, I'll reach out to let you know.

I apologize for not being able to communicate the delay. Thank you for the pull request. 
I've also been attempting to fix the bug on my end (haven't created a pull request yet), and it's similar to your fix. Thank you.

**Comment by mbrandonw** [comment]
Hey @xiii111, sorry about that. I didn't catch that comment. If you've got a PR ready I'll close mine!

**Comment by xiii111** [comment]
Hi @mbrandonw, I am very grateful for your consideration. I will submit a pull request within 24 hours, but essentially it is the same as your modification. Therefore, I have no hesitation in merging your pull request. Please proceed as you see fit.

**Comment by xiii111** [comment]
@mbrandonw I opened #160. Could you check it?

**Comment by mbrandonw** [comment]
Closing in favor of #160.

**Pull request closed without merging**
